// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuCp8sjydX5pyBbZiiZSQtY4gKDnRfcE0',
    appId: '1:208263594321:web:338899bfb40ed1ec401370',
    messagingSenderId: '208263594321',
    projectId: 'craftmyplate-aa7f9',
    authDomain: 'craftmyplate-aa7f9.firebaseapp.com',
    storageBucket: 'craftmyplate-aa7f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAersnJ61BYZwYVShacqnawizqJRKWKlDI',
    appId: '1:208263594321:android:01f82dee7d6d319c401370',
    messagingSenderId: '208263594321',
    projectId: 'craftmyplate-aa7f9',
    storageBucket: 'craftmyplate-aa7f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsiAZTffWuJIeD0eLTCbYZmL98cUxXfy4',
    appId: '1:208263594321:ios:4ada09c6175e5859401370',
    messagingSenderId: '208263594321',
    projectId: 'craftmyplate-aa7f9',
    storageBucket: 'craftmyplate-aa7f9.appspot.com',
    androidClientId: '208263594321-ts7giq3csom7ts194kdgpnl936ffd3li.apps.googleusercontent.com',
    iosClientId: '208263594321-r4jrt487rjdkbb8bji22t6ubees3252n.apps.googleusercontent.com',
    iosBundleId: 'com.example.craftmyplateui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsiAZTffWuJIeD0eLTCbYZmL98cUxXfy4',
    appId: '1:208263594321:ios:55899fa401b0b931401370',
    messagingSenderId: '208263594321',
    projectId: 'craftmyplate-aa7f9',
    storageBucket: 'craftmyplate-aa7f9.appspot.com',
    androidClientId: '208263594321-ts7giq3csom7ts194kdgpnl936ffd3li.apps.googleusercontent.com',
    iosClientId: '208263594321-vqtn7543kt30sa00vjc4mm2frfqsac3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.craftmyplateui.RunnerTests',
  );
}
